---
   environment: development
   chdir: /Users/abushaikh/Code/personal/tweetsh
   address: 127.0.0.1
   port: 4567
   pid: /Users/abushaikh/Code/personal/tweetsh/tmp/thin.pid
   rackup: /Users/abushaikh/Code/personal/tweetsh/config.ru
   log: /Users/abushaikh/Code/personal/tweetsh/log/thin.log
   max_conns: 1024
   timeout: 30
   max_persistent_conns: 512
   daemonize: false
